@startuml

interface sKUma{
    DatabaseData:
    UserAccounts:
    --
    SendDatabaseRequest():
    EditLecture():
    ChangePassword(old,new): boolean
}

class Student{
    Student ID = Person(ID)
    TA: boolean
    CourseList: str
    Education: str
    --
    sKUma.ViewSchedule():
    }

abstract class Person{
Firstname: str
Lastname: str
ID: str
__
Skuma.login()
}

class Admin{
    Employee ID = Person(ID)
    --
    sKUma.EditDatabase():
    sKUma.ViewAllSchedules():
    sKUma.ConfirmRequests():
}

class StudentCounsellor{
    Employee ID = Person(ID)
    --
    sKUma.ViewAllSchedules():
}


class Lecture {
    CourseType:
    Title: coursename + coursetype
    TimeSlot:
    Zoom: Boolean
    --
    }

class Course {
   CourseName:
   StudentList:
   ETCS: int
   Skemagruppe:
   Fakultet:
   --
   }

class CourseLeader{
    Guest: str
    CourseList:
    Employee ID = Person(ID)
    --
    sKUma.RequestEdit():
    sKUma.ViewSchedule():
}

class Database{
    LectureData:
    StudentData:
    EmployeeData:
    ClassRoomData:
    --
    RecreateTables():
    SelectCourses():
    UpdateCourses():
    }

class Room{
Building: str
Floor: int
RoomNr: int
PeopleCapacity: int
Equipment: list
}

class Login{
Username:
Passwword:
Role = Person.Class
}

Room  "1..1" -- "1..*" Database
CourseLeader -- Course
Course -- Lecture
Room - Lecture
sKUma -- Database
sKUma -- Person
Database "1…*" ... "1" Lecture
Student - Course
Person <|-- Admin
Person <|-- CourseLeader
Person <|-- Student
Person <|- StudentCounsellor
Login "1..1" -- "1..*" Database
@enduml


